apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-csrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-csrf
  template:
    metadata:
      labels:
        app: bank-csrf
    spec:
      containers:
        - name: bank-csrf
          image: bank-csrf:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: bank-csrf
spec:
  selector:
    app: bank-csrf
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081