apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
        - name: bank-api
          image: bank-api:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/bank
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: bank-api
spec:
  selector:
    app: bank-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080